# Generated by Django 4.1 on 2022-09-27 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0003_clientes_alter_esteticocorporal_idcliente_and_more'),
        ('Citas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citas',
            name='idCliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Citas', to='Clientes.clientes'),
        ),
        migrations.DeleteModel(
            name='Clientes',
        ),
    ]
