# Generated by Django 4.1 on 2022-11-20 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Citas', '0005_remove_agendacosto_idcita'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agendacosto',
            name='idCliente',
        ),
        migrations.AddField(
            model_name='agendacosto',
            name='idCita',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Citas.citas'),
        ),
    ]
