# Generated by Django 4.1 on 2022-11-20 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0002_alter_clientes_direccion'),
        ('Citas', '0006_remove_agendacosto_idcliente_agendacosto_idcita'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agendacosto',
            name='idCita',
        ),
        migrations.AddField(
            model_name='agendacosto',
            name='idCliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Clientes.clientes'),
        ),
        migrations.AlterField(
            model_name='citas',
            name='idCliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Clientes.clientes'),
        ),
    ]
