# Generated by Django 4.1 on 2022-11-20 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Citas', '0007_remove_agendacosto_idcita_agendacosto_idcliente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendacosto',
            name='idCita',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Citas.citas'),
        ),
    ]
