# Generated by Django 4.1 on 2022-11-05 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sesiones',
        ),
    ]
