# Generated by Django 4.1 on 2022-10-20 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esteticofacial',
            name='alimentosP',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='esteticofacial',
            name='alimentosR',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='esteticofacial',
            name='cualTM',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='esteticofacial',
            name='cualesOT',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='esteticofacial',
            name='cuidadosH',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='esteticofacial',
            name='motivoC',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='esteticofacial',
            name='productoCM',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='esteticofacial',
            name='productoH',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='esteticofacial',
            name='rutinasH',
            field=models.TextField(blank=True, null=True),
        ),
    ]
