# Generated by Django 4.1 on 2022-10-18 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='esteticocorporal',
            old_name='arañitas',
            new_name='aranitas',
        ),
    ]
