# Generated by Django 4.1 on 2022-09-26 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Citas', '0001_initial'),
        ('Clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esteticocorporal',
            name='idCliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Citas.clientes'),
        ),
        migrations.AlterField(
            model_name='esteticofacial',
            name='idCliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Citas.clientes'),
        ),
        migrations.DeleteModel(
            name='Clientes',
        ),
    ]
