# Generated by Django 4.1 on 2022-10-20 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0002_rename_arañitas_esteticocorporal_aranitas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esteticocorporal',
            name='notasO',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='esteticocorporal',
            name='otrosP',
            field=models.TextField(blank=True, null=True),
        ),
    ]
