# Generated by Django 4.1 on 2022-10-25 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0002_alter_esteticofacial_alimentosp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esteticocorporal',
            name='altura',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='esteticocorporal',
            name='kilos',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='esteticocorporal',
            name='masaC',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='esteticocorporal',
            name='talla',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
