# Generated by Django 4.1 on 2022-09-26 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0002_alter_esteticocorporal_idcliente_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('idCliente', models.AutoField(primary_key=True, serialize=False)),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('nombre', models.CharField(max_length=60)),
                ('sexo', models.CharField(blank=True, max_length=9, null=True)),
                ('documento', models.CharField(max_length=10)),
                ('fechaNacimiento', models.CharField(max_length=10)),
                ('telefono', models.CharField(blank=True, max_length=10, null=True)),
                ('direccion', models.CharField(blank=True, max_length=100, null=True)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('estadoCivil', models.CharField(max_length=11)),
                ('numeroHijos', models.CharField(max_length=2)),
                ('fechaActualizacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='esteticocorporal',
            name='idCliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Clientes.clientes'),
        ),
        migrations.AlterField(
            model_name='esteticofacial',
            name='idCliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Clientes.clientes'),
        ),
    ]
