# Generated by Django 4.1 on 2022-10-05 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0003_clientes_alter_esteticocorporal_idcliente_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sesiones',
            fields=[
                ('idSesiones', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.CharField(max_length=10)),
                ('Nseciones', models.CharField(max_length=2)),
                ('valor', models.IntegerField()),
                ('abono', models.IntegerField()),
                ('estado', models.CharField(max_length=9)),
                ('idCorporal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Clientes.esteticocorporal')),
                ('idFacial', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Clientes.esteticofacial')),
            ],
        ),
        migrations.DeleteModel(
            name='Seciones',
        ),
    ]
