# Generated by Django 4.1 on 2022-10-25 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0003_alter_esteticocorporal_altura_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esteticocorporal',
            name='altura',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='esteticocorporal',
            name='kilos',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='esteticocorporal',
            name='masaC',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='esteticocorporal',
            name='talla',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
