# Generated by Django 4.1 on 2022-10-05 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0004_sesiones_delete_seciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='sesiones',
            name='fechaActualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
