# Generated by Django 4.1 on 2022-09-26 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='permisoRol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('idRol', models.AutoField(primary_key=True, serialize=False)),
                ('nombreRol', models.CharField(max_length=60)),
                ('permisoRol', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='RolesPermisos',
            fields=[
                ('idRolesPermisos', models.AutoField(primary_key=True, serialize=False)),
                ('idRol', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='RolesPermisos', to='Configuracion.rol')),
            ],
        ),
    ]
