# Generated by Django 4.1 on 2022-09-29 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('idRol', models.AutoField(primary_key=True, serialize=False)),
                ('nombreRol', models.CharField(max_length=60)),
                ('configuracion', models.CharField(max_length=60)),
                ('insumos', models.CharField(max_length=60)),
                ('citas', models.CharField(max_length=60)),
                ('clientes', models.CharField(max_length=60)),
                ('servicios', models.CharField(max_length=60)),
                ('compras', models.CharField(max_length=60)),
                ('proveedores', models.CharField(max_length=60)),
                ('usuarios', models.CharField(max_length=60)),
            ],
        ),
    ]
