# Generated by Django 4.1 on 2022-11-28 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Configuracion', '0002_group_delete_rol'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Group',
        ),
    ]
