# Generated by Django 4.1 on 2022-09-29 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Configuracion', '0002_rename_nombrerol_rol_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rol',
            name='citas',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='rol',
            name='clientes',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='rol',
            name='compras',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='rol',
            name='configuracion',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='rol',
            name='insumos',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='rol',
            name='proveedores',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='rol',
            name='servicios',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='rol',
            name='usuarios',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
