# Generated by Django 4.1 on 2022-09-27 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Proveedores', '0002_alter_proveedor_correo_alter_proveedor_direccion_and_more'),
        ('Compras', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='proveedor',
        ),
        migrations.AddField(
            model_name='compra',
            name='idProveedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Compra', to='Proveedores.proveedor'),
        ),
    ]
