# Generated by Django 4.1 on 2022-11-15 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Compras', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle_compra',
            name='tipoUnidad',
            field=models.CharField(choices=[(1, 'Unidedes'), (2, 'Mililitros'), (3, 'Gramos')], max_length=14, null=True),
        ),
    ]
