# Generated by Django 4.1 on 2022-11-15 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Compras', '0002_alter_detalle_compra_tipounidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalle_compra',
            name='tipoUnidad',
        ),
    ]
