# Generated by Django 4.1 on 2022-11-07 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Insumos', '0007_remove_insumo_nombre_insumo_nombreinsumo'),
        ('Compras', '0002_remove_compra_proveedor_compra_idproveedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='idInsumo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Compra', to='Insumos.insumo'),
        ),
    ]
