# Generated by Django 4.1 on 2022-11-10 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Compras', '0003_compra_idinsumo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='idInsumo',
        ),
    ]
