# Generated by Django 4.1 on 2022-11-18 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Compras', '0003_remove_detalle_compra_tipounidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='ValorTotal',
            field=models.FloatField(max_length=10),
        ),
        migrations.AlterField(
            model_name='detalle_compra',
            name='costoUnidad',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='detalle_compra',
            name='subTotal',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='detalle_compra',
            name='total',
            field=models.FloatField(null=True),
        ),
    ]
