# Generated by Django 4.1 on 2022-11-10 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Compras', '0004_remove_compra_idinsumo'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalle_compra',
            name='cantidad',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='detalle_compra',
            name='costoUnidad',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='detalle_compra',
            name='subTotal',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='detalle_compra',
            name='tipoUnidad',
            field=models.CharField(max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='detalle_compra',
            name='total',
            field=models.IntegerField(null=True),
        ),
    ]
