# Generated by Django 4.1 on 2022-11-18 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Compras', '0004_alter_compra_valortotal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalle_compra',
            name='unidad',
            field=models.IntegerField(null=True),
        ),
    ]
