# Generated by Django 4.1 on 2022-11-22 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Compras', '0006_alter_compra_valortotal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='ValorTotal',
            field=models.FloatField(max_length=10),
        ),
    ]
