# Generated by Django 4.1 on 2022-11-22 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Compras', '0007_alter_compra_valortotal'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='estadoC',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
    ]
