# Generated by Django 4.1 on 2022-11-26 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Compras', '0008_compra_estadoc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='ValorTotal',
            field=models.CharField(max_length=14),
        ),
        migrations.AlterField(
            model_name='detalle_compra',
            name='subTotal',
            field=models.CharField(max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='detalle_compra',
            name='total',
            field=models.CharField(max_length=14, null=True),
        ),
    ]
