# Generated by Django 4.1 on 2022-11-08 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Insumos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insumo',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='insumo',
            name='nombre',
        ),
        migrations.AddField(
            model_name='insumo',
            name='gramos',
            field=models.CharField(max_length=4, null=True, verbose_name='Gramos'),
        ),
        migrations.AddField(
            model_name='insumo',
            name='nombreInsumo',
            field=models.TextField(null=True, verbose_name='NombreInsumo'),
        ),
        migrations.AddField(
            model_name='insumo',
            name='unidades',
            field=models.CharField(max_length=4, null=True, verbose_name='Unidades'),
        ),
    ]
