# Generated by Django 4.1 on 2022-11-15 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Insumos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumo',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
    ]
