# Generated by Django 4.1 on 2022-09-20 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Insumos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumo',
            name='valorTotal',
            field=models.CharField(max_length=7, null=True, verbose_name='ValorT'),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='cantidad',
            field=models.CharField(max_length=3, null=True, verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='numeroFactura',
            field=models.CharField(max_length=5, null=True, verbose_name='NumeroF'),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='producto',
            field=models.TextField(null=True, verbose_name='Producto'),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='proveedor',
            field=models.TextField(null=True, verbose_name='Proveedor'),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='valorUnidad',
            field=models.CharField(max_length=7, verbose_name='ValorU'),
        ),
    ]
