# Generated by Django 4.1 on 2022-09-22 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Insumos', '0002_insumo_valortotal_alter_insumo_cantidad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insumo',
            name='numeroFactura',
        ),
        migrations.RemoveField(
            model_name='insumo',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='insumo',
            name='proveedor',
        ),
        migrations.RemoveField(
            model_name='insumo',
            name='valorTotal',
        ),
        migrations.RemoveField(
            model_name='insumo',
            name='valorUnidad',
        ),
        migrations.AddField(
            model_name='insumo',
            name='insumo',
            field=models.TextField(null=True, verbose_name='Insumo'),
        ),
    ]
