# Generated by Django 4.1 on 2022-09-26 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Insumos', '0004_remove_insumo_insumo_insumo_nombre_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='insumo',
            old_name='id',
            new_name='idInsumos',
        ),
    ]
