# Generated by Django 4.1 on 2022-09-27 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Insumos', '0005_rename_id_insumo_idinsumos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='insumo',
            old_name='idInsumos',
            new_name='idInsumo',
        ),
    ]
