# Generated by Django 4.1 on 2022-11-07 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Insumos', '0006_rename_idinsumos_insumo_idinsumo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insumo',
            name='nombre',
        ),
        migrations.AddField(
            model_name='insumo',
            name='nombreInsumo',
            field=models.TextField(null=True, verbose_name='Insumo'),
        ),
    ]
