# Generated by Django 4.1 on 2022-11-10 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Insumos', '0007_remove_insumo_nombre_insumo_nombreinsumo'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumo',
            name='tipoUnidad',
            field=models.CharField(max_length=14, null=True),
        ),
    ]
