# Generated by Django 4.1 on 2022-11-11 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Insumos', '0008_insumo_tipounidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumo',
            name='cantidad',
            field=models.CharField(default=0, max_length=4, verbose_name='Cantidad'),
        ),
    ]
