# Generated by Django 4.1 on 2022-11-11 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Insumos', '0009_alter_insumo_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumo',
            name='cantidad',
            field=models.IntegerField(default=0, verbose_name='Cantidad'),
        ),
    ]
