# Generated by Django 4.1 on 2022-10-13 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('idProveedor', models.AutoField(primary_key=True, serialize=False)),
                ('proveedor', models.CharField(max_length=30)),
                ('producto', models.CharField(max_length=30)),
                ('telefono', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=30)),
                ('correo', models.CharField(max_length=40)),
                ('direccion', models.CharField(max_length=40)),
            ],
        ),
    ]
