# Generated by Django 4.1 on 2022-09-26 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proveedores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='correo',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='direccion',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='nombre',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='producto',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='proveedor',
            field=models.CharField(max_length=30),
        ),
    ]
