<<<<<<< HEAD
# Generated by Django 4.1 on 2022-11-05 00:15
=======
<<<<<<< Updated upstream
# Generated by Django 4.1 on 2022-10-14 13:24
=======
# Generated by Django 4.1 on 2022-11-08 15:09
>>>>>>> Stashed changes
>>>>>>> dayana

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Insumos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('idServicio', models.AutoField(primary_key=True, serialize=False)),
                ('nServicio', models.CharField(max_length=50)),
                ('tiempo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Servicios_Insumo',
            fields=[
                ('idServicios_Insumo', models.AutoField(primary_key=True, serialize=False)),
                ('idInsumo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Insumos.insumo')),
                ('idServicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Servicios.servicios')),
            ],
        ),
    ]
