# Generated by Django 4.1 on 2022-10-14 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('idServicio', models.AutoField(primary_key=True, serialize=False)),
                ('nServicio', models.CharField(max_length=50)),
                ('tiempo', models.IntegerField()),
            ],
        ),
    ]
