# Generated by Django 4.1 on 2022-11-27 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Servicios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicios',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
