# Generated by Django 4.1 on 2022-11-20 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Servicios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicios',
            name='valor',
            field=models.IntegerField(default=0),
        ),
    ]
