# Generated by Django 4.1 on 2022-11-01 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Insumos', '0001_initial'),
        ('Servicios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicios_Insumo',
            fields=[
                ('idServicios_Insumo', models.AutoField(primary_key=True, serialize=False)),
                ('idInsumo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Insumos.insumo')),
                ('idServicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Servicios.servicios')),
            ],
        ),
    ]
