# Generated by Django 4.1 on 2022-11-20 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Servicios', '0002_servicios_valor'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicios_insumo',
            name='cantidadUsada',
            field=models.IntegerField(default=0),
        ),
    ]
