<<<<<<< HEAD
# Generated by Django 4.1 on 2022-09-16 02:29
=======
# Generated by Django 4.1 on 2022-09-16 06:42
>>>>>>> usuarios

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='Prueba',
            fields=[
                ('idPrueba', models.AutoField(primary_key=True, serialize=False)),
                ('at1', models.CharField(max_length=11)),
                ('at2', models.CharField(max_length=11)),
                ('at3', models.CharField(max_length=11)),
=======
            name='Usuarios',
            fields=[
                ('idUsuario', models.AutoField(primary_key=True, serialize=False)),
                ('documento', models.CharField(max_length=10)),
                ('nUsuario', models.CharField(max_length=20)),
                ('contrasena', models.CharField(max_length=20)),
                ('correo', models.EmailField(max_length=254)),
                ('fechaCreacion', models.DateTimeField(auto_now=True)),
>>>>>>> usuarios
            ],
        ),
    ]