# Generated by Django 4.1 on 2022-11-17 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuarios',
        ),
    ]
