# Generated by Django 4.1 on 2022-09-25 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='nPersona',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='correo',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
