# Generated by Django 4.1 on 2022-10-07 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0003_alter_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='nUsuario',
        ),
    ]
